#!/usr/bin/env python3
"""Accuracy comparison: clax.ept vs CLASS-PT reference spectra.

Loads reference data generated by CLASS-PT (via classy), runs clax.ept
on the same P_lin input, and reports relative errors for every observable.

Usage:
    conda run -n sbi_pytorch_osx-arm64-py310forge python3 scripts/accuracy_classpt.py

Exit code 0 if all spectra pass <1% max relative error at k < 0.3 h/Mpc.
"""

from __future__ import annotations

import os
import sys

import numpy as np

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO)

try:
    import jax
    import jax.numpy as jnp
    jax.config.update("jax_enable_x64", True)
except ImportError:
    print("ERROR: JAX not found. Activate conda env: sbi_pytorch_osx-arm64-py310forge")
    sys.exit(1)

from clax.ept import (
    compute_ept, EPTPrecisionParams,
    pk_mm_real, pk_gg_real, pk_gm_real,
    pk_mm_l0, pk_mm_l2, pk_mm_l4,
    pk_gg_l0, pk_gg_l2, pk_gg_l4,
)

# ---------------------------------------------------------------------------
# Load reference data
# ---------------------------------------------------------------------------

REF_FILE = os.path.join(_REPO, "reference_data", "classpt_z0.38_fullrange.npz")
if not os.path.isfile(REF_FILE):
    print(f"ERROR: reference file not found: {REF_FILE}")
    print("Run: conda run -n sbi_pytorch_osx-arm64-py310forge "
          "python3 scripts/generate_classpt_reference.py")
    sys.exit(1)

ref = np.load(REF_FILE, allow_pickle=True)
k_h    = ref["k_h"]           # (256,) h/Mpc
z      = float(ref["z"])
h      = float(ref["h"])
f      = float(ref["fz"])
pk_lin = ref["pk_lin"]         # (256,) (Mpc/h)^3

# Bias / EFT parameters used when generating reference
b = {
    "b1":       float(ref["bias_b1"]),
    "b2":       float(ref["bias_b2"]),
    "bG2":      float(ref["bias_bG2"]),
    "bGamma3":  float(ref["bias_bGamma3"]),
    "cs0":      float(ref["bias_cs0"]),
    "cs2":      float(ref["bias_cs2"]),
    "cs4":      float(ref["bias_cs4"]),
    "Pshot":    float(ref["bias_Pshot"]),
    "b4":       float(ref["bias_b4"]),
    "cs":       float(ref["bias_cs"]),
}

print(f"Reference: z={z:.2f}, h={h:.4f}, f={f:.4f}")
print(f"k grid: {len(k_h)} points [{k_h.min():.4f}, {k_h.max():.1f}] h/Mpc")
print(f"Bias: b1={b['b1']}, b2={b['b2']}, bG2={b['bG2']}, bGamma3={b['bGamma3']}")
print(f"EFT:  cs0={b['cs0']}, cs2={b['cs2']}, cs4={b['cs4']}, Pshot={b['Pshot']:.0f}\n")

# ---------------------------------------------------------------------------
# Run clax.ept
# ---------------------------------------------------------------------------

print("Running compute_ept ...")
prec = EPTPrecisionParams()
ept_out = compute_ept(jnp.array(pk_lin), jnp.array(k_h), h=h, f=f, prec=prec)
print(f"  Sigma_BAO^2 check (expect ~30-50 (Mpc/h)^2): "
      f"computed from IR resummation (not directly accessible)")
print(f"  Pk_tree range: [{float(ept_out.Pk_tree.min()):.1f}, {float(ept_out.Pk_tree.max()):.1f}]")
print(f"  Pk_loop range: [{float(ept_out.Pk_loop.min()):.1f}, {float(ept_out.Pk_loop.max()):.1f}]")

# ---------------------------------------------------------------------------
# Compute clax spectra
# ---------------------------------------------------------------------------

clax = {
    "pk_mm_real": np.array(pk_mm_real(ept_out, cs0=b["cs0"])),
    "pk_gg_real": np.array(pk_gg_real(
        ept_out, b["b1"], b["b2"], b["bG2"], b["bGamma3"],
        cs=b["cs"], cs0=b["cs0"], Pshot=b["Pshot"])),
    "pk_gm_real": np.array(pk_gm_real(
        ept_out, b["b1"], b["b2"], b["bG2"], b["bGamma3"],
        cs0=b["cs0"], cs=b["cs"])),
    "pk_mm_l0": np.array(pk_mm_l0(ept_out, cs0=b["cs0"])),
    "pk_mm_l2": np.array(pk_mm_l2(ept_out, cs2=b["cs2"])),
    "pk_mm_l4": np.array(pk_mm_l4(ept_out, cs4=b["cs4"])),
    "pk_gg_l0": np.array(pk_gg_l0(
        ept_out, b["b1"], b["b2"], b["bG2"], b["bGamma3"],
        cs0=b["cs0"], Pshot=b["Pshot"], b4=b["b4"])),
    "pk_gg_l2": np.array(pk_gg_l2(
        ept_out, b["b1"], b["b2"], b["bG2"], b["bGamma3"],
        cs2=b["cs2"], b4=b["b4"])),
    "pk_gg_l4": np.array(pk_gg_l4(
        ept_out, b["b1"], b["b2"], b["bG2"], b["bGamma3"],
        cs4=b["cs4"], b4=b["b4"])),
}

ref_spectra = {
    "pk_mm_real": np.squeeze(ref["pk_mm_real"]),
    "pk_gg_real": np.squeeze(ref["pk_gg_real"]),
    "pk_gm_real": np.squeeze(ref["pk_mg_real"]),
    "pk_mm_l0":   np.squeeze(ref["pk_mm_l0"]),
    "pk_mm_l2":   np.squeeze(ref["pk_mm_l2"]),
    "pk_mm_l4":   np.squeeze(ref["pk_mm_l4"]),
    "pk_gg_l0":   np.squeeze(ref["pk_gg_l0"]),
    "pk_gg_l2":   np.squeeze(ref["pk_gg_l2"]),
    "pk_gg_l4":   np.squeeze(ref["pk_gg_l4"]),
}

# ---------------------------------------------------------------------------
# Compute relative errors at k < 0.3 h/Mpc (perturbative regime)
# ---------------------------------------------------------------------------

K_MAX_COMPARE = 0.3   # h/Mpc — PT validity cutoff
mask = k_h < K_MAX_COMPARE
k_compare = k_h[mask]

print(f"\nAccuracy at k < {K_MAX_COMPARE} h/Mpc ({mask.sum()} modes):\n")
# l=4 multipoles: use absolute error normalized to max(|ref|) < 1% as the
# pass criterion.  The hexadecapole crosses near zero at k~0.25 h/Mpc, so
# relative errors blow up even when the absolute accuracy is excellent.
# All other spectra use relative error < 1%.
L4_NAMES = {"pk_mm_l4", "pk_gg_l4"}
THRESH_L4   = 0.02   # |clax-ref| / max(|ref|) < 2% for l=4
THRESH_L02  = 0.01   # |clax-ref| / |ref|     < 1% for l=0,2 and real-space
VALID_L02   = 0.01   # skip |ref| < 1% of max for l=0,2

HEADER = f"{'Spectrum':<16} {'max_err':>9} {'mean_err':>9} {'k@max':>8}  {'pass':>8}  {'metric':>12}"
print(HEADER)
print("-" * len(HEADER))

all_pass = True
results = {}
for name in clax:
    c = clax[name][mask]
    r = ref_spectra[name][mask]

    abs_ref = np.abs(r)
    is_l4   = name in L4_NAMES

    if is_l4:
        # Absolute-normalised error: |Δ| / max(|ref|) — robust to near-zero crossings
        ref_scale = abs_ref.max()
        valid = np.ones(len(c), dtype=bool)  # use all k
        abs_err = np.abs(c - r)
        norm_err = abs_err / ref_scale
        max_err  = float(norm_err.max())
        mean_err = float(norm_err.mean())
        k_at_max = float(k_compare[norm_err.argmax()])
        passed   = max_err < THRESH_L4
        metric   = "abs/max(ref)"
    else:
        valid = abs_ref > VALID_L02 * abs_ref.max()
        if valid.sum() < 5:
            print(f"  {name:<16}  (skipped — too few valid points)")
            continue
        rel_err  = np.abs(c[valid] - r[valid]) / abs_ref[valid]
        max_err  = float(rel_err.max())
        mean_err = float(rel_err.mean())
        k_at_max = float(k_compare[valid][rel_err.argmax()])
        passed   = max_err < THRESH_L02
        metric   = "rel"

    results[name] = dict(max_err=max_err, mean_err=mean_err, k_at_max=k_at_max)
    symbol = "✓" if passed else "✗"
    print(f"  {name:<16} {max_err:>8.2%} {mean_err:>9.2%} {k_at_max:>8.4f}  "
          f"{symbol} {'PASS' if passed else 'FAIL'}  {metric:>12}")
    if not passed:
        all_pass = False

# ---------------------------------------------------------------------------
# Detailed diagnostic for failing spectra
# ---------------------------------------------------------------------------

print(f"\n--- Diagnostic: 5-point comparison at k = 0.05, 0.1, 0.15, 0.2, 0.25 h/Mpc ---")
k_diag = np.array([0.05, 0.10, 0.15, 0.20, 0.25])
for name in ["pk_mm_real", "pk_gg_real", "pk_mm_l0"]:
    if name not in clax:
        continue
    c_all = clax[name]
    r_all = ref_spectra[name]
    print(f"\n  {name}:")
    print(f"  {'k':>8}  {'clax':>14}  {'CLASS-PT':>14}  {'rel_err':>10}")
    for kd in k_diag:
        idx = np.argmin(np.abs(k_h - kd))
        c_v = c_all[idx]
        r_v = r_all[idx]
        err = abs(c_v - r_v) / max(abs(r_v), 1e-10)
        print(f"  {k_h[idx]:8.4f}  {c_v:14.3f}  {r_v:14.3f}  {err:10.3%}")

# ---------------------------------------------------------------------------
# Save plot
# ---------------------------------------------------------------------------

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    os.makedirs(os.path.join(_REPO, "docs"), exist_ok=True)
    fig, axes = plt.subplots(3, 3, figsize=(14, 10))
    axes = axes.flatten()

    names_ordered = list(clax.keys())
    for ax, name in zip(axes, names_ordered):
        c = clax[name]
        r = ref_spectra[name]
        abs_ref = np.abs(r)
        valid = abs_ref > 0.01 * abs_ref.max()
        rel_err = np.where(valid, np.abs(c - r) / np.where(abs_ref > 0, abs_ref, 1), np.nan)

        ax.semilogy(k_h, rel_err * 100, "b-", lw=1.2, label="clax vs CLASS-PT")
        ax.axvline(K_MAX_COMPARE, color="gray", ls="--", lw=0.8, label=f"k={K_MAX_COMPARE}")
        ax.axhline(1.0, color="r", ls="--", lw=0.8, label="1% threshold")
        ax.set_xlim(0, 0.5)
        ax.set_ylim(1e-3, 100)
        ax.set_xlabel("k [h/Mpc]")
        ax.set_ylabel("|Δ/ref| [%]")
        ax.set_title(name)
        ax.legend(fontsize=7)

    fig.suptitle(f"clax.ept vs CLASS-PT accuracy (z={z:.2f})", fontsize=13)
    fig.tight_layout()
    outpath = os.path.join(_REPO, "docs", "accuracy_comparison.png")
    fig.savefig(outpath, dpi=150)
    print(f"\nPlot saved: {outpath}")
except Exception as e:
    print(f"\n(Plot skipped: {e})")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

print(f"\n{'='*50}")
if all_pass:
    print("ALL SPECTRA PASS (l0,l2 < 1%; l4 < 2%) at k < 0.3 h/Mpc  ✓")
else:
    failing = [n for n, r in results.items()
               if r["max_err"] >= (THRESH_L4 if n in L4_NAMES else THRESH_L02)]
    print(f"FAILING spectra ({len(failing)}): {', '.join(failing)}")
    print("Check diagnostic output above for clues.")
print(f"{'='*50}")

sys.exit(0 if all_pass else 1)
